/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author justx
 */
public class CadastroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form PaginaCadastroVagas
     */
    public CadastroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbl_noneCad = new javax.swing.JLabel();
        txt_nomeCad = new javax.swing.JTextField();
        btn_VoltarCad = new javax.swing.JButton();
        panel_quadLarCadas = new javax.swing.JPanel();
        lbl_logoCadas = new javax.swing.JLabel();
        lbl_cadasCanaisCadas = new javax.swing.JLabel();
        txt_senhaCad = new javax.swing.JPasswordField();
        btn_salvarCad = new javax.swing.JButton();
        jCheckBox_VisualSenhaCad = new javax.swing.JCheckBox();
        lbl_senhaCad = new javax.swing.JLabel();
        lbl_crieSuaConta = new javax.swing.JLabel();
        lbl_usuarioCad = new javax.swing.JLabel();
        txt_usuarioCad = new javax.swing.JTextField();
        txt_emailCad = new javax.swing.JTextField();
        lbl_emailCad = new javax.swing.JLabel();
        lbl_confSenhaCad = new javax.swing.JLabel();
        txt_confSenhaCad = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 630));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_noneCad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_noneCad.setForeground(new java.awt.Color(45, 18, 75));
        lbl_noneCad.setText("Nome");
        jPanel2.add(lbl_noneCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        txt_nomeCad.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        txt_nomeCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeCadActionPerformed(evt);
            }
        });
        jPanel2.add(txt_nomeCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 500, 40));

        btn_VoltarCad.setBackground(new java.awt.Color(204, 204, 204));
        btn_VoltarCad.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_VoltarCad.setText("Voltar");
        btn_VoltarCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VoltarCadActionPerformed(evt);
            }
        });
        jPanel2.add(btn_VoltarCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 200, 60));

        panel_quadLarCadas.setBackground(new java.awt.Color(255, 62, 21));

        lbl_logoCadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Untitled-removebg-preview.png"))); // NOI18N

        lbl_cadasCanaisCadas.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_cadasCanaisCadas.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cadasCanaisCadas.setText("Cadastro");

        javax.swing.GroupLayout panel_quadLarCadasLayout = new javax.swing.GroupLayout(panel_quadLarCadas);
        panel_quadLarCadas.setLayout(panel_quadLarCadasLayout);
        panel_quadLarCadasLayout.setHorizontalGroup(
            panel_quadLarCadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_quadLarCadasLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lbl_cadasCanaisCadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 746, Short.MAX_VALUE)
                .addComponent(lbl_logoCadas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        panel_quadLarCadasLayout.setVerticalGroup(
            panel_quadLarCadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_quadLarCadasLayout.createSequentialGroup()
                .addGroup(panel_quadLarCadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_quadLarCadasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_logoCadas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_quadLarCadasLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lbl_cadasCanaisCadas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(panel_quadLarCadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 1240, 140));

        txt_senhaCad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel2.add(txt_senhaCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 500, 40));

        btn_salvarCad.setBackground(new java.awt.Color(255, 62, 21));
        btn_salvarCad.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btn_salvarCad.setForeground(new java.awt.Color(255, 255, 255));
        btn_salvarCad.setText("Cadastrar");
        btn_salvarCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarCadActionPerformed(evt);
            }
        });
        jPanel2.add(btn_salvarCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 550, 200, 60));

        jCheckBox_VisualSenhaCad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox_VisualSenhaCad.setForeground(new java.awt.Color(45, 18, 75));
        jCheckBox_VisualSenhaCad.setText("Visualizar a Senha");
        jCheckBox_VisualSenhaCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_VisualSenhaCadActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox_VisualSenhaCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, -1, -1));

        lbl_senhaCad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_senhaCad.setForeground(new java.awt.Color(45, 18, 75));
        lbl_senhaCad.setText("Senha");
        jPanel2.add(lbl_senhaCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        lbl_crieSuaConta.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_crieSuaConta.setForeground(new java.awt.Color(45, 18, 75));
        lbl_crieSuaConta.setText("Crie sua conta");
        jPanel2.add(lbl_crieSuaConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));

        lbl_usuarioCad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_usuarioCad.setForeground(new java.awt.Color(45, 18, 75));
        lbl_usuarioCad.setText("Usuario");
        jPanel2.add(lbl_usuarioCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        txt_usuarioCad.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        txt_usuarioCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioCadActionPerformed(evt);
            }
        });
        jPanel2.add(txt_usuarioCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 500, 40));

        txt_emailCad.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        txt_emailCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailCadActionPerformed(evt);
            }
        });
        jPanel2.add(txt_emailCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 500, 40));

        lbl_emailCad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_emailCad.setForeground(new java.awt.Color(45, 18, 75));
        lbl_emailCad.setText("E-mail");
        jPanel2.add(lbl_emailCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, -1, -1));

        lbl_confSenhaCad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_confSenhaCad.setForeground(new java.awt.Color(45, 18, 75));
        lbl_confSenhaCad.setText("Confirmar Senha");
        jPanel2.add(lbl_confSenhaCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, -1, 20));

        txt_confSenhaCad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel2.add(txt_confSenhaCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, 500, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_VoltarCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VoltarCadActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
	this.dispose();
    }//GEN-LAST:event_btn_VoltarCadActionPerformed

    private void txt_nomeCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeCadActionPerformed

    private void btn_salvarCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarCadActionPerformed
        // TODO add your handling code here:
        new CadastroSucesso().setVisible(true);
	this.dispose();
    }//GEN-LAST:event_btn_salvarCadActionPerformed

    private void jCheckBox_VisualSenhaCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_VisualSenhaCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_VisualSenhaCadActionPerformed

    private void txt_usuarioCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioCadActionPerformed

    private void txt_emailCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailCadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_VoltarCad;
    private javax.swing.JButton btn_salvarCad;
    private javax.swing.JCheckBox jCheckBox_VisualSenhaCad;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_cadasCanaisCadas;
    private javax.swing.JLabel lbl_confSenhaCad;
    private javax.swing.JLabel lbl_crieSuaConta;
    private javax.swing.JLabel lbl_emailCad;
    private javax.swing.JLabel lbl_logoCadas;
    private javax.swing.JLabel lbl_noneCad;
    private javax.swing.JLabel lbl_senhaCad;
    private javax.swing.JLabel lbl_usuarioCad;
    private javax.swing.JPanel panel_quadLarCadas;
    private javax.swing.JPasswordField txt_confSenhaCad;
    private javax.swing.JTextField txt_emailCad;
    private javax.swing.JTextField txt_nomeCad;
    private javax.swing.JPasswordField txt_senhaCad;
    private javax.swing.JTextField txt_usuarioCad;
    // End of variables declaration//GEN-END:variables
}
