/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author rodri
 */
public class LoginAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form Login1
     */
    public LoginAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel_LogoAdm = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        lbl_SubTitleAdm1 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        lbl_SubTitleAdm2 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        lbl_SubTitleAdm3 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbl_LoginAdmTitle = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lbl_TipoGerenciador = new javax.swing.JLabel();
        txt_usuarioLogin = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lbl_TipoSenhaAdm = new javax.swing.JLabel();
        txt_senhaLogin = new javax.swing.JPasswordField();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jCheckBox_VisualizarSenhaAdm = new javax.swing.JCheckBox();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        btn_EntrarAdm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMinimumSize(new java.awt.Dimension(850, 600));
        setPreferredSize(new java.awt.Dimension(1200, 630));

        jPanel1.setBackground(new java.awt.Color(255, 62, 21));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 630));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel16.setBackground(new java.awt.Color(255, 62, 21));
        jPanel16.setPreferredSize(new java.awt.Dimension(320, 200));
        jPanel16.setLayout(new java.awt.GridBagLayout());

        jLabel_LogoAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Untitled-removebg-preview.png"))); // NOI18N
        jPanel16.add(jLabel_LogoAdm, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel16, java.awt.BorderLayout.PAGE_START);

        jPanel17.setBackground(new java.awt.Color(255, 62, 21));
        jPanel17.setLayout(new java.awt.BorderLayout());

        jPanel18.setBackground(new java.awt.Color(255, 62, 21));
        jPanel18.setPreferredSize(new java.awt.Dimension(350, 50));
        jPanel18.setLayout(new java.awt.GridBagLayout());

        lbl_SubTitleAdm1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_SubTitleAdm1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_SubTitleAdm1.setText("Aqui você cria os canais");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 81, 13, 81);
        jPanel18.add(lbl_SubTitleAdm1, gridBagConstraints);

        jPanel17.add(jPanel18, java.awt.BorderLayout.PAGE_START);

        jPanel19.setBackground(new java.awt.Color(255, 62, 21));
        jPanel19.setLayout(new java.awt.BorderLayout());

        jPanel21.setBackground(new java.awt.Color(255, 62, 21));
        jPanel21.setPreferredSize(new java.awt.Dimension(350, 50));
        jPanel21.setLayout(new java.awt.GridBagLayout());

        lbl_SubTitleAdm2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_SubTitleAdm2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_SubTitleAdm2.setText("para os usuários");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 83, 13, 84);
        jPanel21.add(lbl_SubTitleAdm2, gridBagConstraints);

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel21.add(jPanel24, new java.awt.GridBagConstraints());

        jPanel19.add(jPanel21, java.awt.BorderLayout.PAGE_START);

        jPanel20.setBackground(new java.awt.Color(255, 62, 21));
        jPanel20.setLayout(new java.awt.BorderLayout());

        jPanel22.setBackground(new java.awt.Color(255, 62, 21));
        jPanel22.setPreferredSize(new java.awt.Dimension(350, 50));
        jPanel22.setLayout(new java.awt.GridBagLayout());

        lbl_SubTitleAdm3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_SubTitleAdm3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_SubTitleAdm3.setText("configurar suas vendas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 70, 13, 71);
        jPanel22.add(lbl_SubTitleAdm3, gridBagConstraints);

        jPanel20.add(jPanel22, java.awt.BorderLayout.PAGE_START);

        jPanel23.setBackground(new java.awt.Color(255, 62, 21));
        jPanel23.setLayout(new java.awt.BorderLayout());

        jPanel25.setBackground(new java.awt.Color(255, 62, 21));
        jPanel25.setPreferredSize(new java.awt.Dimension(350, 50));
        jPanel25.setLayout(new java.awt.GridBagLayout());
        jPanel23.add(jPanel25, java.awt.BorderLayout.PAGE_START);

        jPanel26.setBackground(new java.awt.Color(255, 62, 21));
        jPanel26.setLayout(new java.awt.BorderLayout());

        jPanel27.setBackground(new java.awt.Color(255, 62, 21));
        jPanel27.setPreferredSize(new java.awt.Dimension(350, 50));
        jPanel27.setLayout(new java.awt.GridBagLayout());
        jPanel26.add(jPanel27, java.awt.BorderLayout.PAGE_START);

        jPanel23.add(jPanel26, java.awt.BorderLayout.CENTER);

        jPanel20.add(jPanel23, java.awt.BorderLayout.CENTER);

        jPanel19.add(jPanel20, java.awt.BorderLayout.CENTER);

        jPanel17.add(jPanel19, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel17, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel2.setBackground(new java.awt.Color(241, 241, 241));
        jPanel2.setPreferredSize(new java.awt.Dimension(1020, 630));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(241, 241, 241));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        lbl_LoginAdmTitle.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        lbl_LoginAdmTitle.setForeground(new java.awt.Color(45, 18, 75));
        lbl_LoginAdmTitle.setText("Login Administrativo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 200, 61, 250);
        jPanel3.add(lbl_LoginAdmTitle, gridBagConstraints);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(241, 241, 241));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(241, 241, 241));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        lbl_TipoGerenciador.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_TipoGerenciador.setForeground(new java.awt.Color(45, 18, 75));
        lbl_TipoGerenciador.setText("Gerenciador");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 180, 0, 0);
        jPanel5.add(lbl_TipoGerenciador, gridBagConstraints);

        txt_usuarioLogin.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        txt_usuarioLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 436;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 180, 24, 170);
        jPanel5.add(txt_usuarioLogin, gridBagConstraints);

        jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(241, 241, 241));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(241, 241, 241));
        jPanel7.setPreferredSize(new java.awt.Dimension(850, 80));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        lbl_TipoSenhaAdm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_TipoSenhaAdm.setForeground(new java.awt.Color(45, 18, 75));
        lbl_TipoSenhaAdm.setText("Senha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 179, 0, 0);
        jPanel7.add(lbl_TipoSenhaAdm, gridBagConstraints);

        txt_senhaLogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 436;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 179, 10, 171);
        jPanel7.add(txt_senhaLogin, gridBagConstraints);

        jPanel6.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel8.setBackground(new java.awt.Color(241, 241, 241));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(241, 241, 241));
        jPanel9.setPreferredSize(new java.awt.Dimension(850, 50));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        jCheckBox_VisualizarSenhaAdm.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jCheckBox_VisualizarSenhaAdm.setForeground(new java.awt.Color(45, 18, 75));
        jCheckBox_VisualizarSenhaAdm.setText("Visualizar a Senha");
        jCheckBox_VisualizarSenhaAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_VisualizarSenhaAdmActionPerformed(evt);
            }
        });
        jPanel9.add(jCheckBox_VisualizarSenhaAdm, new java.awt.GridBagConstraints());

        jPanel8.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel10.setBackground(new java.awt.Color(241, 241, 241));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel11.setBackground(new java.awt.Color(241, 241, 241));
        jPanel11.setMinimumSize(new java.awt.Dimension(100, 80));
        jPanel11.setPreferredSize(new java.awt.Dimension(850, 60));
        jPanel11.setLayout(new java.awt.GridBagLayout());

        btn_EntrarAdm.setBackground(new java.awt.Color(204, 204, 204));
        btn_EntrarAdm.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_EntrarAdm.setText("Entrar");
        btn_EntrarAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EntrarAdmActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 68;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 320, 26, 330);
        jPanel11.add(btn_EntrarAdm, gridBagConstraints);

        jPanel10.add(jPanel11, java.awt.BorderLayout.PAGE_START);

        jPanel8.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usuarioLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioLoginActionPerformed

    private void jCheckBox_VisualizarSenhaAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_VisualizarSenhaAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_VisualizarSenhaAdmActionPerformed

    private void btn_EntrarAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EntrarAdmActionPerformed
        // TODO add your handling code here:
        new PaginaCadastroVagas().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btn_EntrarAdmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_EntrarAdm;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckBox_VisualizarSenhaAdm;
    private javax.swing.JLabel jLabel_LogoAdm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbl_LoginAdmTitle;
    private javax.swing.JLabel lbl_SubTitleAdm1;
    private javax.swing.JLabel lbl_SubTitleAdm2;
    private javax.swing.JLabel lbl_SubTitleAdm3;
    private javax.swing.JLabel lbl_TipoGerenciador;
    private javax.swing.JLabel lbl_TipoSenhaAdm;
    private javax.swing.JPasswordField txt_senhaLogin;
    private javax.swing.JTextField txt_usuarioLogin;
    // End of variables declaration//GEN-END:variables
}
