  /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author justx
 */
public class PaginaCadastroInfoUs extends javax.swing.JFrame {

    /**
     * Creates new form PaginaCadastroInfoUs
     */
    public PaginaCadastroInfoUs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbl_logoInfoUs = new javax.swing.JLabel();
        lbl_4dGroupInfoUs = new javax.swing.JLabel();
        lbl_CompInfoUs = new javax.swing.JLabel();
        lbl_cadasCanaInfoUs = new javax.swing.JLabel();
        txt_idCadasInfoUs = new javax.swing.JTextField();
        lbl_idContaInfoUs = new javax.swing.JLabel();
        txt_senhaInfoUs = new javax.swing.JTextField();
        lbl_senhaInfoUs = new javax.swing.JLabel();
        txt_userInfoUs = new javax.swing.JTextField();
        lbl_userInfoUs = new javax.swing.JLabel();
        lbl_canalInfoUs = new javax.swing.JLabel();
        btn_cadastrarInfoUs = new javax.swing.JButton();
        panel_quadLaraInfoUs = new javax.swing.JPanel();
        lbl_canalCadasInfoUs = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 630));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_logoInfoUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Untitled-removebg-preview.png"))); // NOI18N
        jPanel2.add(lbl_logoInfoUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 120));

        lbl_4dGroupInfoUs.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        lbl_4dGroupInfoUs.setForeground(new java.awt.Color(45, 18, 75));
        lbl_4dGroupInfoUs.setText("4D Group");
        jPanel2.add(lbl_4dGroupInfoUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        lbl_CompInfoUs.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_CompInfoUs.setForeground(new java.awt.Color(45, 18, 75));
        lbl_CompInfoUs.setText("Company");
        jPanel2.add(lbl_CompInfoUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        lbl_cadasCanaInfoUs.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_cadasCanaInfoUs.setForeground(new java.awt.Color(45, 18, 75));
        lbl_cadasCanaInfoUs.setText("Cadastro de Canais ");
        jPanel2.add(lbl_cadasCanaInfoUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        txt_idCadasInfoUs.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_idCadasInfoUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idCadasInfoUsActionPerformed(evt);
            }
        });
        jPanel2.add(txt_idCadasInfoUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 230, 40));

        lbl_idContaInfoUs.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_idContaInfoUs.setForeground(new java.awt.Color(45, 18, 75));
        lbl_idContaInfoUs.setText("ID da Conta");
        jPanel2.add(lbl_idContaInfoUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, -1, -1));

        txt_senhaInfoUs.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_senhaInfoUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_senhaInfoUsActionPerformed(evt);
            }
        });
        jPanel2.add(txt_senhaInfoUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 230, 40));

        lbl_senhaInfoUs.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_senhaInfoUs.setForeground(new java.awt.Color(45, 18, 75));
        lbl_senhaInfoUs.setText("Senha");
        jPanel2.add(lbl_senhaInfoUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, -1, -1));

        txt_userInfoUs.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_userInfoUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userInfoUsActionPerformed(evt);
            }
        });
        jPanel2.add(txt_userInfoUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 230, 40));

        lbl_userInfoUs.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_userInfoUs.setForeground(new java.awt.Color(45, 18, 75));
        lbl_userInfoUs.setText("Usuário");
        jPanel2.add(lbl_userInfoUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        lbl_canalInfoUs.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_canalInfoUs.setForeground(new java.awt.Color(45, 18, 75));
        lbl_canalInfoUs.setText("Canal");
        jPanel2.add(lbl_canalInfoUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        btn_cadastrarInfoUs.setBackground(new java.awt.Color(255, 62, 21));
        btn_cadastrarInfoUs.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_cadastrarInfoUs.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastrarInfoUs.setText("Cadastrar");
        btn_cadastrarInfoUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarInfoUsActionPerformed(evt);
            }
        });
        jPanel2.add(btn_cadastrarInfoUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, 200, 60));

        panel_quadLaraInfoUs.setBackground(new java.awt.Color(255, 62, 21));

        javax.swing.GroupLayout panel_quadLaraInfoUsLayout = new javax.swing.GroupLayout(panel_quadLaraInfoUs);
        panel_quadLaraInfoUs.setLayout(panel_quadLaraInfoUsLayout);
        panel_quadLaraInfoUsLayout.setHorizontalGroup(
            panel_quadLaraInfoUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        panel_quadLaraInfoUsLayout.setVerticalGroup(
            panel_quadLaraInfoUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        jPanel2.add(panel_quadLaraInfoUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, -1, -1));

        lbl_canalCadasInfoUs.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_canalCadasInfoUs.setText("Aqui ficara o canal cadastrado!");
        jPanel2.add(lbl_canalCadasInfoUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 230, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel2.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_userInfoUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userInfoUsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userInfoUsActionPerformed

    private void txt_senhaInfoUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_senhaInfoUsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_senhaInfoUsActionPerformed

    private void txt_idCadasInfoUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idCadasInfoUsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idCadasInfoUsActionPerformed

    private void btn_cadastrarInfoUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarInfoUsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cadastrarInfoUsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaCadastroInfoUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaCadastroInfoUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaCadastroInfoUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaCadastroInfoUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaCadastroInfoUs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrarInfoUs;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_4dGroupInfoUs;
    private javax.swing.JLabel lbl_CompInfoUs;
    private javax.swing.JLabel lbl_cadasCanaInfoUs;
    private javax.swing.JLabel lbl_canalCadasInfoUs;
    private javax.swing.JLabel lbl_canalInfoUs;
    private javax.swing.JLabel lbl_idContaInfoUs;
    private javax.swing.JLabel lbl_logoInfoUs;
    private javax.swing.JLabel lbl_senhaInfoUs;
    private javax.swing.JLabel lbl_userInfoUs;
    private javax.swing.JPanel panel_quadLaraInfoUs;
    private javax.swing.JTextField txt_idCadasInfoUs;
    private javax.swing.JTextField txt_senhaInfoUs;
    private javax.swing.JTextField txt_userInfoUs;
    // End of variables declaration//GEN-END:variables
}
