/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author justx
 */
public class PaginaCadastroVagas extends javax.swing.JFrame {

    /**
     * Creates new form PaginaCadastroVagas
     */
    public PaginaCadastroVagas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbl_logoCadas = new javax.swing.JLabel();
        lbl_4dGroupCadas = new javax.swing.JLabel();
        lbl_companyCadas = new javax.swing.JLabel();
        lbl_cadasCanaisCadas = new javax.swing.JLabel();
        lbl_canalCadas = new javax.swing.JLabel();
        txt_canalCadas = new javax.swing.JTextField();
        cmb_TipoCanalCadas = new javax.swing.JComboBox<>();
        lbl_TipoCanalCadas = new javax.swing.JLabel();
        cmb_padAutCadas = new javax.swing.JComboBox<>();
        lbl_padAutCadas = new javax.swing.JLabel();
        btn_salvarCadas = new javax.swing.JButton();
        panel_quadLarCadas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 630));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_logoCadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Untitled-removebg-preview.png"))); // NOI18N
        jPanel2.add(lbl_logoCadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 120));

        lbl_4dGroupCadas.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        lbl_4dGroupCadas.setForeground(new java.awt.Color(45, 18, 75));
        lbl_4dGroupCadas.setText("4D Group");
        jPanel2.add(lbl_4dGroupCadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        lbl_companyCadas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_companyCadas.setForeground(new java.awt.Color(45, 18, 75));
        lbl_companyCadas.setText("Company");
        jPanel2.add(lbl_companyCadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        lbl_cadasCanaisCadas.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_cadasCanaisCadas.setForeground(new java.awt.Color(45, 18, 75));
        lbl_cadasCanaisCadas.setText("Cadastro de Canais ");
        jPanel2.add(lbl_cadasCanaisCadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        lbl_canalCadas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_canalCadas.setForeground(new java.awt.Color(45, 18, 75));
        lbl_canalCadas.setText("Canal");
        jPanel2.add(lbl_canalCadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        txt_canalCadas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_canalCadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_canalCadasActionPerformed(evt);
            }
        });
        jPanel2.add(txt_canalCadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 270, 40));

        cmb_TipoCanalCadas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cmb_TipoCanalCadas.setForeground(new java.awt.Color(45, 18, 75));
        cmb_TipoCanalCadas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MarketPlace", "Plataforma/ERP", "Meio de Pagamento" }));
        jPanel2.add(cmb_TipoCanalCadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, 40));

        lbl_TipoCanalCadas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_TipoCanalCadas.setForeground(new java.awt.Color(45, 18, 75));
        lbl_TipoCanalCadas.setText("Tipo de Canal");
        jPanel2.add(lbl_TipoCanalCadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));

        cmb_padAutCadas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cmb_padAutCadas.setForeground(new java.awt.Color(45, 18, 75));
        cmb_padAutCadas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuário e Senha", "Token", " " }));
        jPanel2.add(cmb_padAutCadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 240, 40));

        lbl_padAutCadas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_padAutCadas.setForeground(new java.awt.Color(45, 18, 75));
        lbl_padAutCadas.setText("Padrão de Autenticação");
        jPanel2.add(lbl_padAutCadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, -1, -1));

        btn_salvarCadas.setBackground(new java.awt.Color(255, 62, 21));
        btn_salvarCadas.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_salvarCadas.setForeground(new java.awt.Color(255, 255, 255));
        btn_salvarCadas.setText("Salvar");
        btn_salvarCadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarCadasActionPerformed(evt);
            }
        });
        jPanel2.add(btn_salvarCadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, 200, 60));

        panel_quadLarCadas.setBackground(new java.awt.Color(255, 62, 21));

        javax.swing.GroupLayout panel_quadLarCadasLayout = new javax.swing.GroupLayout(panel_quadLarCadas);
        panel_quadLarCadas.setLayout(panel_quadLarCadasLayout);
        panel_quadLarCadasLayout.setHorizontalGroup(
            panel_quadLarCadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        panel_quadLarCadasLayout.setVerticalGroup(
            panel_quadLarCadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        jPanel2.add(panel_quadLarCadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salvarCadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarCadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salvarCadasActionPerformed

    private void txt_canalCadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_canalCadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_canalCadasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaCadastroVagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaCadastroVagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaCadastroVagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaCadastroVagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaCadastroVagas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_salvarCadas;
    private javax.swing.JComboBox<String> cmb_TipoCanalCadas;
    private javax.swing.JComboBox<String> cmb_padAutCadas;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_4dGroupCadas;
    private javax.swing.JLabel lbl_TipoCanalCadas;
    private javax.swing.JLabel lbl_cadasCanaisCadas;
    private javax.swing.JLabel lbl_canalCadas;
    private javax.swing.JLabel lbl_companyCadas;
    private javax.swing.JLabel lbl_logoCadas;
    private javax.swing.JLabel lbl_padAutCadas;
    private javax.swing.JPanel panel_quadLarCadas;
    private javax.swing.JTextField txt_canalCadas;
    // End of variables declaration//GEN-END:variables
}
