/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author justx
 */
public class PaginaInfoCaTo extends javax.swing.JFrame {

    /**
     * Creates new form PaginaInfoCaTo
     */
    public PaginaInfoCaTo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_telacadastro = new javax.swing.JPanel();
        lbl_logoInfoTo = new javax.swing.JLabel();
        lbl_4dgroupInfoTo = new javax.swing.JLabel();
        lbl_companyInfoTo = new javax.swing.JLabel();
        panel_quadLaranja = new javax.swing.JPanel();
        txt_IddacontaInfoTo = new javax.swing.JTextField();
        lbl_idDacontaInfoTo = new javax.swing.JLabel();
        lbl_canalInfoTo = new javax.swing.JLabel();
        lbl_tokenInfoTo = new javax.swing.JLabel();
        txt_tokenInfoTo = new javax.swing.JTextField();
        btn_cadasInfoTo = new javax.swing.JButton();
        lbl_subTituloInfoTo = new javax.swing.JLabel();
        lbl_canalCadasInfoTo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_telacadastro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_telacadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel_telacadastro.setPreferredSize(new java.awt.Dimension(1200, 630));
        panel_telacadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_logoInfoTo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Untitled-removebg-preview.png"))); // NOI18N
        panel_telacadastro.add(lbl_logoInfoTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 120));

        lbl_4dgroupInfoTo.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        lbl_4dgroupInfoTo.setForeground(new java.awt.Color(45, 18, 75));
        lbl_4dgroupInfoTo.setText("4D Group");
        panel_telacadastro.add(lbl_4dgroupInfoTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        lbl_companyInfoTo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_companyInfoTo.setForeground(new java.awt.Color(45, 18, 75));
        lbl_companyInfoTo.setText("Company");
        panel_telacadastro.add(lbl_companyInfoTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        panel_quadLaranja.setBackground(new java.awt.Color(255, 62, 21));

        javax.swing.GroupLayout panel_quadLaranjaLayout = new javax.swing.GroupLayout(panel_quadLaranja);
        panel_quadLaranja.setLayout(panel_quadLaranjaLayout);
        panel_quadLaranjaLayout.setHorizontalGroup(
            panel_quadLaranjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        panel_quadLaranjaLayout.setVerticalGroup(
            panel_quadLaranjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel_telacadastro.add(panel_quadLaranja, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, -1, 640));

        txt_IddacontaInfoTo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_IddacontaInfoTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IddacontaInfoToActionPerformed(evt);
            }
        });
        panel_telacadastro.add(txt_IddacontaInfoTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 230, 40));

        lbl_idDacontaInfoTo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_idDacontaInfoTo.setForeground(new java.awt.Color(45, 18, 75));
        lbl_idDacontaInfoTo.setText("ID da Conta");
        panel_telacadastro.add(lbl_idDacontaInfoTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, -1));

        lbl_canalInfoTo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_canalInfoTo.setForeground(new java.awt.Color(45, 18, 75));
        lbl_canalInfoTo.setText("Canal");
        panel_telacadastro.add(lbl_canalInfoTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        lbl_tokenInfoTo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_tokenInfoTo.setForeground(new java.awt.Color(45, 18, 75));
        lbl_tokenInfoTo.setText("Token");
        panel_telacadastro.add(lbl_tokenInfoTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        txt_tokenInfoTo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_tokenInfoTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tokenInfoToActionPerformed(evt);
            }
        });
        panel_telacadastro.add(txt_tokenInfoTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 230, 40));

        btn_cadasInfoTo.setBackground(new java.awt.Color(255, 62, 21));
        btn_cadasInfoTo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_cadasInfoTo.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadasInfoTo.setText("Cadastrar");
        btn_cadasInfoTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadasInfoToActionPerformed(evt);
            }
        });
        panel_telacadastro.add(btn_cadasInfoTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, 200, 60));

        lbl_subTituloInfoTo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_subTituloInfoTo.setForeground(new java.awt.Color(45, 18, 75));
        lbl_subTituloInfoTo.setText("Cadastro de Canais ");
        panel_telacadastro.add(lbl_subTituloInfoTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        lbl_canalCadasInfoTo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_canalCadasInfoTo.setText("Aqui ficara o canal cadastrado!");
        panel_telacadastro.add(lbl_canalCadasInfoTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 230, 40));

        getContentPane().add(panel_telacadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tokenInfoToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tokenInfoToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tokenInfoToActionPerformed

    private void txt_IddacontaInfoToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IddacontaInfoToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IddacontaInfoToActionPerformed

    private void btn_cadasInfoToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadasInfoToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cadasInfoToActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaInfoCaTo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaInfoCaTo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaInfoCaTo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaInfoCaTo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaInfoCaTo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadasInfoTo;
    private javax.swing.JLabel lbl_4dgroupInfoTo;
    private javax.swing.JLabel lbl_canalCadasInfoTo;
    private javax.swing.JLabel lbl_canalInfoTo;
    private javax.swing.JLabel lbl_companyInfoTo;
    private javax.swing.JLabel lbl_idDacontaInfoTo;
    private javax.swing.JLabel lbl_logoInfoTo;
    private javax.swing.JLabel lbl_subTituloInfoTo;
    private javax.swing.JLabel lbl_tokenInfoTo;
    private javax.swing.JPanel panel_quadLaranja;
    private javax.swing.JPanel panel_telacadastro;
    private javax.swing.JTextField txt_IddacontaInfoTo;
    private javax.swing.JTextField txt_tokenInfoTo;
    // End of variables declaration//GEN-END:variables
}
