/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author justx
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PaginaCadastroVagas
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbl_LoginTitle = new javax.swing.JLabel();
        panel_quadLarLogin = new javax.swing.JPanel();
        lbl_logoCadas = new javax.swing.JLabel();
        lbl_SubTitleLogin1 = new javax.swing.JLabel();
        lbl_SubTitleLogin4 = new javax.swing.JLabel();
        lbl_SubTitleLogin5 = new javax.swing.JLabel();
        lbl_SubTitleLogin6 = new javax.swing.JLabel();
        btn_cadastreUser = new javax.swing.JButton();
        btn_cadastreUser1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 630));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_LoginTitle.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_LoginTitle.setForeground(new java.awt.Color(45, 18, 75));
        lbl_LoginTitle.setText("Bem Vindo");
        jPanel2.add(lbl_LoginTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        panel_quadLarLogin.setBackground(new java.awt.Color(255, 62, 21));

        lbl_logoCadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Untitled-removebg-preview.png"))); // NOI18N

        lbl_SubTitleLogin1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_SubTitleLogin1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_SubTitleLogin1.setText("abaixo");

        lbl_SubTitleLogin4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_SubTitleLogin4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_SubTitleLogin4.setText("clicando no ");

        lbl_SubTitleLogin5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_SubTitleLogin5.setForeground(new java.awt.Color(191, 191, 191));
        lbl_SubTitleLogin5.setText("botão");

        lbl_SubTitleLogin6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_SubTitleLogin6.setForeground(new java.awt.Color(255, 255, 255));
        lbl_SubTitleLogin6.setText("Crie agora mesmo");

        btn_cadastreUser.setBackground(new java.awt.Color(45, 18, 75));
        btn_cadastreUser.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btn_cadastreUser.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastreUser.setText("Cadastrar");
        btn_cadastreUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastreUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_quadLarLoginLayout = new javax.swing.GroupLayout(panel_quadLarLogin);
        panel_quadLarLogin.setLayout(panel_quadLarLoginLayout);
        panel_quadLarLoginLayout.setHorizontalGroup(
            panel_quadLarLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_quadLarLoginLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(panel_quadLarLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_quadLarLoginLayout.createSequentialGroup()
                        .addComponent(lbl_logoCadas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_quadLarLoginLayout.createSequentialGroup()
                        .addGroup(panel_quadLarLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_SubTitleLogin6)
                            .addGroup(panel_quadLarLoginLayout.createSequentialGroup()
                                .addComponent(lbl_SubTitleLogin4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_SubTitleLogin5)))
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_quadLarLoginLayout.createSequentialGroup()
                        .addComponent(lbl_SubTitleLogin1)
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_quadLarLoginLayout.createSequentialGroup()
                        .addComponent(btn_cadastreUser, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
        panel_quadLarLoginLayout.setVerticalGroup(
            panel_quadLarLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_quadLarLoginLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lbl_logoCadas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(lbl_SubTitleLogin6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_quadLarLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SubTitleLogin4)
                    .addComponent(lbl_SubTitleLogin5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_SubTitleLogin1)
                .addGap(51, 51, 51)
                .addComponent(btn_cadastreUser, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jPanel2.add(panel_quadLarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, -1, -1));

        btn_cadastreUser1.setBackground(new java.awt.Color(255, 62, 21));
        btn_cadastreUser1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btn_cadastreUser1.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastreUser1.setText("Logar");
        btn_cadastreUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastreUser1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_cadastreUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, 200, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastreUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastreUserActionPerformed
        // TODO add your handling code here:
        new CadastroUsuario().setVisible(true);
	this.dispose();
    }//GEN-LAST:event_btn_cadastreUserActionPerformed

    private void btn_cadastreUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastreUser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cadastreUser1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastreUser;
    private javax.swing.JButton btn_cadastreUser1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_LoginTitle;
    private javax.swing.JLabel lbl_SubTitleLogin1;
    private javax.swing.JLabel lbl_SubTitleLogin4;
    private javax.swing.JLabel lbl_SubTitleLogin5;
    private javax.swing.JLabel lbl_SubTitleLogin6;
    private javax.swing.JLabel lbl_logoCadas;
    private javax.swing.JPanel panel_quadLarLogin;
    // End of variables declaration//GEN-END:variables
}
